#!/bin/bash

# Install go
curl https://dl.google.com/go/go1.11.1.linux-amd64.tar.gz -O
sudo tar -C /usr/local -xzf go1.11.1.linux-amd64.tar.gz
go get -u mvdan.cc/sh/cmd/shfmt

# Install docker-ce, and necessary packages
distro=$(lsb_release -si)
if [ "$distro" = "Fedora" ]; then
  sudo dnf -y install dnf-plugins-core cmake gcc-c++ make python3-devel
  sudo dnf config-manager \
      --add-repo \
      https://download.docker.com/linux/fedora/docker-ce.repo

  sudo dnf -y install docker-ce
  sudo systemctl enable docker && sudo systemctl start docker
  sudo usermod -aG docker $(whoami)
fi

curl -L https://github.com/pyenv/pyenv-installer/raw/master/bin/pyenv-installer | bash
pyenv install 3.7.1

# Configure ViM
curl -fLo ~/.vim/autoload/plug.vim --create-dirs \
    https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
vim +PlugInstall

